### ISSUE TITLE
Lancement s2p sur tristereo Melbourne

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#1]
Objectif
======
L'objectif est de lancer s2p sur la tristereo Melbourne pour obtenir une Image3D.

Faire cette issue une fois #3 réalisée. Ensuite:
- mettre l'image détectée dans #3 en première image dans le config.json de s2p
- eventuellement tester sur une roi
- utiliser l'option netcdf et la branche add_netcdf_support

Notes
=====
Pour l'obtention de l'image 3D au format netcdf il conviendra d'utiliser le s2p suivant : 
https://github.com/dumasl/s2p
et choisir la branche "add_netcdf_support"

**Comment by nguyen0508** [comment]
Monsieur,
Pourriez-vous ajouter Martin à ce projet github, s'il vous plaît? Son compte est "mseymour24".

**Comment by dumasl** [comment]
En utilisant la branche add_netcdf_support vous devriez pouvoir trouver des fichier *.nc dans les tiles/row*/col*

Pour ouvrir ces fichiers vous pouvez installer xarray (pip install xarray) puis 

```python
>>> import xarray as xr
>>> xr.open_dataset('cloud3D_image.nc')
<xarray.Dataset>
Dimensions:            (i: 350, j: 350, x: 3, y: 350, z: 350)
Dimensions without coordinates: i, j, x, y, z
Data variables:
    band_0             (i, j) int32 ...
    nb_views           (i, j) int32 ...
    nodata             (i, j) int32 ...
    radius             (i, j) float32 ...
    secondary_1        (i, j) int32 ...
    secondary_2        (i, j) int32 ...
    dir_view_1_vector  (x, y, z) int32 ...
    dir_view_1_origin  (x, y, z) int32 ...
    dir_view_2_vector  (x, y, z) int32 ...
    dir_view_2_origin  (x, y, z) int32 ...
    dir_view_3_vector  (x, y, z) int32 ...
    dir_view_3_origin  (x, y, z) int32 ...
    coord_ECEF         (x, y, z) float64 ...
```

**Comment by nguyen0508** [comment]
J'ai bien trouvé le fichier "cloud3D_image.nc". Je l'ai ouvert avec xarray, j'ai retrouvé exactement ce qu'il me faut. 

Merci Monsieur,
