### ISSUE TITLE
Installation de s2p

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#2]
Objectif
======

Installer s2p pour pouvoir effectuer l'issue #1

**Comment by dumasl** [comment]
@nguyen0508 N'hésitez pas à nous faire savoir si vous rencontrez ou avez rencontré des difficultés

**Comment by nguyen0508** [comment]
Monsieur,

Nous sommes déjà bien sur la branche "add_netcdf_support" de "https://github.com/dumasl/s2p"

(la sortie de la commande git checkout add_netcdf_support est
"Already on 'add_netcdf_support'
Your branch is up to date with 'origin/add_netcdf_support'.")

 mais nous n'arrivons pas à installer s2p avec la commande "make all" car il nous retourne une erreur suivante:
 
"bin/netcdf: In function `writeNetCDFFile':
netcdf.c:(.text+0x382): undefined reference to `nc_create'
netcdf.c:(.text+0x3b4): undefined reference to `nc_def_dim'
netcdf.c:(.text+0x3df): undefined reference to `nc_def_dim'
netcdf.c:(.text+0x405): undefined reference to `nc_def_dim'
netcdf.c:(.text+0x42d): undefined reference to `nc_def_dim'
netcdf.c:(.text+0x451): undefined reference to `nc_def_dim'
netcdf.c:(.text+0x520): undefined reference to `nc_def_var'
netcdf.c:(.text+0x56f): undefined reference to `nc_def_var'
netcdf.c:(.text+0x59e): undefined reference to `nc_def_var'
netcdf.c:(.text+0x5cd): undefined reference to `nc_def_var'
netcdf.c:(.text+0x663): undefined reference to `nc_def_var'
bin/netcdf:netcdf.c:(.text+0x71b): more undefined references to `nc_def_var' follow
bin/netcdf: In function `writeNetCDFFile':
netcdf.c:(.text+0x7c4): undefined reference to `nc_enddef'
netcdf.c:(.text+0x8d0): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0x904): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0x921): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0x93e): undefined reference to `nc_put_var_float'
netcdf.c:(.text+0xa48): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0xc04): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0xcaa): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0xcee): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0xd01): undefined reference to `nc_close'
netcdf.c:(.text+0xdc6): undefined reference to `nc_put_var_int'
netcdf.c:(.text+0xe00): undefined reference to `nc_strerror'
netcdf.c:(.text+0xe2e): undefined reference to `nc_strerror'
netcdf.c:(.text+0xe62): undefined reference to `nc_strerror'
collect2: error: ld returned 1 exit status
makefile:165: recipe for target 'bin/multidisp2ply' failed
make: *** [bin/multidisp2ply] Error 1"

Pourriez-vous nous dire comment le résoudre, s'il vous plaît?

**Comment by dumasl** [comment]
Après la phase compilation de s2p, le compilateur essaie de résoudre les liens entre les fonctions de s2p qui utilisent des librairies externes, et lesdites librairies externes.

Plus précisément en regardant le message d'erreur (merci de l'avoir recopié ici), on note que lors de la génération de "bin/multidisp2ply":
>  makefile:165: recipe for target 'bin/multidisp2ply' failed

qui s'appuie vraisemblablement sur le fichier netcdf.c de s2p, l'édition des liens échoue (undefined reference to '').
> bin/netcdf: In function writeNetCDFFile': netcdf.c:(.text+0x382): undefined reference to nc_create'

Cela veut dire que le fichier netcdf.c s'appuie sur des méthodes qui n'ont pas pu être trouvée lors de l'édition des liens (toutes les méthodes qui suivent le message 'undefined reference to').

Ici on s'aperçoit que toutes ces méthodes commencent par 'nc_' et on peut en déduire qu'il s'agit de méthodes livrées avec le package netcdf système (rien à voir avec le fichier netcdf.c de s2p qui aurait pu s'appeler toto.c sans que rien n'y change).

Donc, deux possibilités:
- soit vous n'avez pas netcdf d'installer sur l'ordinateur sur lequel vous avez essayé de compiler s2p
- sot vous avez bien netcdf mais le programme système qui réalise l'édition de lien (qui tente de faire le lien entre les méthodes de s2p et les méthodes netcdf dont s2p dépend) ne trouve pas votre paquet netcdf système.

Pour le savoir, essayez la commande:
```sh
yum install netdcdf-devel
# ou bien sur une distribution debian (ubuntu par exemple), ce doit être
apt-get install libnetcdf-dev
```

Si le résultat de la commande vous indique qu'il n'y a rien à faire car le paquet est déjà installé c'est donc que lors de l'édition des liens votre système n'arrive pas à retrouver votre paquet (le paquet netdf est bien installé mais pas dans un endroit classique aux yeux du système). 
Dans ce cas il vous faut vous même localiser netcdf sur votre ordinateur puis renseigner la variable d'environnement LIBRARY_PATH:

```sh
export LIBRARY_PATH=$LIBRARY_PATH:your_netcdf_path
```

Le compilateur utilisera alors le chemin présent dans LIBRARY_PATH pour résoudre les références vers les méthodes netcdf.


Faites moi savoir si ce n'est pas clair.
