### ISSUE TITLE
Detection de la PAN étant fournie avec les XS

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#3]
Objectif
======

Utiliser monteverdi pour faire le lien entre la PMS du répertoire pan-sharpened et les P du triplet pléiades.
Ceci pour pouvoir utiliser la PAN fournie avec la PMS en tant qu'image référence dans s2p pour résourdre l'issue #1 

Notes
=====
L'image de référence dans s2p est la première image citée dans le confi.json

**Comment by nguyen0508** [comment]
Monsieur,

Pourriez-vous nous dire qu'est-ce que c'est un PMS et un répertoire pan-sharpened s'il vous plaît?

**Comment by nguyen0508** [comment]
Monsieur,

En untilisant monteverdi, j'ai visualé un peu l'image XS (trois bandes de couleurs R,G,B) du répertoire pan-sharpened et les trois images PAN (en noire et blanc) du triplet pléiades mais je ne sais pas très bien comment faire le lien entre eux,  pouvez-vous détailler un peu plus, s'il vous plaît?

**Comment by dumasl** [comment]
Le triplet est livré avec trois PAN (image en niveau de gris à haute résolution = un pixel couvre une très petite zone surfacique terrestre < 1m).

Pouvez me rappeler si le dossier que vous avez en votre possession, et qui contient l'image couleur, se nomme Product-Primary-Bundle ou Product-Primary-Pan-sharpened?

**Comment by nguyen0508** [comment]
Il est nommé Product-Primary-Pan-sharpened.
