### ISSUE TITLE
Installation de l'otb

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#4]
installation de l'otb

**Comment by nguyen0508** [comment]
Monsieur,

J'ai installé OTB sur ubuntu avec la command "sudo apt-get install otb-bin python3-otb". Comme il y en a pleins de package, je ne sais pas si j'ai bien installé tout ce qu'il me faut. Je mets donc  la sortie de "aptitude search otb" ici, pouvez-vous me dire s'il y a encore des packages qu'il me faut encore installer, s'il vous plaît?

nguyen@nguyen-Inspiron-5545:~$ aptitude search otb
 p   libotb                          - ORFEO Toolbox library metapackage         
p   libotb:i386                     - ORFEO Toolbox library metapackage         
i A libotb-apps                     - Plugins for ORFEO Toolbox applications    
p   libotb-apps:i386                - Plugins for ORFEO Toolbox applications    
p   libotb-dev                      - Free library of image processing algorithm
p   libotb-dev:i386                 - Free library of image processing algorithm
i A libotbapplicationengine-6.4-1   - ORFEO Toolbox library - OTBApplicationEngi
p   libotbapplicationengine-6.4-1:i - ORFEO Toolbox library - OTBApplicationEngi
i A libotbcarto-6.4-1               - ORFEO Toolbox library - OTBCarto          
p   libotbcarto-6.4-1:i386          - ORFEO Toolbox library - OTBCarto          
i A libotbcommandline-6.4-1         - ORFEO Toolbox library - OTBCommandLine    
p   libotbcommandline-6.4-1:i386    - ORFEO Toolbox library - OTBCommandLine    
i A libotbcommandlineparser-6.4-1   - ORFEO Toolbox library - OTBCommandLinePase
p   libotbcommandlineparser-6.4-1:i - ORFEO Toolbox library - OTBCommandLinePase
i A libotbcommon-6.4-1              - ORFEO Toolbox library - OTBCommon         
p   libotbcommon-6.4-1:i386         - ORFEO Toolbox library - OTBCommon         
i A libotbcurladapters-6.4-1        - ORFEO Toolbox library - OTBCurlAdapters   
p   libotbcurladapters-6.4-1:i386   - ORFEO Toolbox library - OTBCurlAdapters   
i A libotbedge-6.4-1                - ORFEO Toolbox library - OTBEdge           
p   libotbedge-6.4-1:i386           - ORFEO Toolbox library - OTBEdge           
i A libotbextendedfilename-6.4-1    - ORFEO Toolbox library - OTBExtendedFileNam
p   libotbextendedfilename-6.4-1:i3 - ORFEO Toolbox library - OTBExtendedFileNam
i A libotbfuzzy-6.4-1               - ORFEO Toolbox library - OTBFuzzy          
p   libotbfuzzy-6.4-1:i386          - ORFEO Toolbox library - OTBFuzzy          
i A libotbgdaladapters-6.4-1        - ORFEO Toolbox library - OTBGdalAdapters   
p   libotbgdaladapters-6.4-1:i386   - ORFEO Toolbox library - OTBGdalAdapters   
i A libotbice-6.4-1                 - ORFEO Toolbox library - OTBIce            
p   libotbice-6.4-1:i386            - ORFEO Toolbox library - OTBIce            
i A libotbimagebase-6.4-1           - ORFEO Toolbox library - OTBImageBase      
p   libotbimagebase-6.4-1:i386      - ORFEO Toolbox library - OTBImageBase      
i A libotbimageio-6.4-1             - ORFEO Toolbox library - OTBImageIO        
p   libotbimageio-6.4-1:i386        - ORFEO Toolbox library - OTBImageIO        
i A libotbimagemanipulation-6.4-1   - ORFEO Toolbox library - OTBImageManipulati
p   libotbimagemanipulation-6.4-1:i - ORFEO Toolbox library - OTBImageManipulati
i A libotbiobsq-6.4-1               - ORFEO Toolbox library - OTBIOBSQ          
p   libotbiobsq-6.4-1:i386          - ORFEO Toolbox library - OTBIOBSQ          
i A libotbiogdal-6.4-1              - ORFEO Toolbox library - OTBIOGDAL         
p   libotbiogdal-6.4-1:i386         - ORFEO Toolbox library - OTBIOGDAL         
i A libotbiokml-6.4-1               - ORFEO Toolbox library - OTBIOKML          
p   libotbiokml-6.4-1:i386          - ORFEO Toolbox library - OTBIOKML          
i A libotbiolum-6.4-1               - ORFEO Toolbox library - OTBIOLUM          
p   libotbiolum-6.4-1:i386          - ORFEO Toolbox library - OTBIOLUM          
i A libotbiomstar-6.4-1             - ORFEO Toolbox library - OTBIOMSTAR        
p   libotbiomstar-6.4-1:i386        - ORFEO Toolbox library - OTBIOMSTAR        
i A libotbioonera-6.4-1             - ORFEO Toolbox library - OTBIOONERA        
p   libotbioonera-6.4-1:i386        - ORFEO Toolbox library - OTBIOONERA        
i A libotbiorad-6.4-1               - ORFEO Toolbox library - OTBIORAD          
p   libotbiorad-6.4-1:i386          - ORFEO Toolbox library - OTBIORAD          
i A libotbiotilemap-6.4-1           - ORFEO Toolbox library - OTBIOTileMap      
p   libotbiotilemap-6.4-1:i386      - ORFEO Toolbox library - OTBIOTileMap      
i A libotbmapla-6.4-1               - ORFEO Toolbox library - OTBMapla          
p   libotbmapla-6.4-1:i386          - ORFEO Toolbox library - OTBMapla          
i A libotbmathparser-6.4-1          - ORFEO Toolbox library - OTBMathParser     
p   libotbmathparser-6.4-1:i386     - ORFEO Toolbox library - OTBMathParser     
i A libotbmetadata-6.4-1            - ORFEO Toolbox library - OTBMetadata       
p   libotbmetadata-6.4-1:i386       - ORFEO Toolbox library - OTBMetadata       
i A libotbmonteverdi-6.4-1          - ORFEO Toolbox library - OTBMonteverdi     
p   libotbmonteverdi-6.4-1:i386     - ORFEO Toolbox library - OTBMonteverdi     
i A libotbmonteverdicore-6.4-1      - ORFEO Toolbox library - OTBMonteverdiCore 
p   libotbmonteverdicore-6.4-1:i386 - ORFEO Toolbox library - OTBMonteverdiCore 
i A libotbmonteverdigui-6.4-1       - ORFEO Toolbox library - OTBMonteverdiGUI  
p   libotbmonteverdigui-6.4-1:i386  - ORFEO Toolbox library - OTBMonteverdiGUI  
i A libotbopenthreadsadapters-6.4-1 - ORFEO Toolbox library - OTBOpenThreadsAdap
p   libotbopenthreadsadapters-6.4-1 - ORFEO Toolbox library - OTBOpenThreadsAdap
i A libotbossimadapters-6.4-1       - ORFEO Toolbox library - OTBOssimAdapters  
p   libotbossimadapters-6.4-1:i386  - ORFEO Toolbox library - OTBOssimAdapters  
i A libotbossimplugins-6.4-1        - ORFEO Toolbox library - OTBOssimPlugins   
p   libotbossimplugins-6.4-1:i386   - ORFEO Toolbox library - OTBOssimPlugins   
i A libotbpolarimetry-6.4-1         - ORFEO Toolbox library - OTBPolarimetry    
p   libotbpolarimetry-6.4-1:i386    - ORFEO Toolbox library - OTBPolarimetry    
i A libotbprojection-6.4-1          - ORFEO Toolbox library - OTBProjection     
p   libotbprojection-6.4-1:i386     - ORFEO Toolbox library - OTBProjection     
i A libotbqtadapters-6.4-1          - ORFEO Toolbox library - OTBQtAdapters     
p   libotbqtadapters-6.4-1:i386     - ORFEO Toolbox library - OTBQtAdapters     
i A libotbqtwidget-6.4-1            - ORFEO Toolbox library - OTBQtWidget       
p   libotbqtwidget-6.4-1:i386       - ORFEO Toolbox library - OTBQtWidget       
i A libotbrcc8-6.4-1                - ORFEO Toolbox library - OTBRCC8           
p   libotbrcc8-6.4-1:i386           - ORFEO Toolbox library - OTBRCC8           
i A libotbsampling-6.4-1            - ORFEO Toolbox library - OTBSampling       
p   libotbsampling-6.4-1:i386       - ORFEO Toolbox library - OTBSampling       
i A libotbsiftfast-6.4-1            - ORFEO Toolbox library - OTBSiftFast       
p   libotbsiftfast-6.4-1:i386       - ORFEO Toolbox library - OTBSiftFast       
i A libotbstatistics-6.4-1          - ORFEO Toolbox library - OTBStatistics     
p   libotbstatistics-6.4-1:i386     - ORFEO Toolbox library - OTBStatistics     
i A libotbstreaming-6.4-1           - ORFEO Toolbox library - OTBStreaming      
p   libotbstreaming-6.4-1:i386      - ORFEO Toolbox library - OTBStreaming      
i A libotbsupervised-6.4-1          - ORFEO Toolbox library - OTBSupervised     
p   libotbsupervised-6.4-1:i386     - ORFEO Toolbox library - OTBSupervised     
i A libotbtestkernel-6.4-1          - ORFEO Toolbox library - OTBTestKernel     
p   libotbtestkernel-6.4-1:i386     - ORFEO Toolbox library - OTBTestKernel     
i A libotbtransform-6.4-1           - ORFEO Toolbox library - OTBTransform      
p   libotbtransform-6.4-1:i386      - ORFEO Toolbox library - OTBTransform      
i A libotbvectordatabase-6.4-1      - ORFEO Toolbox library - OTBVectorDataBase 
p   libotbvectordatabase-6.4-1:i386 - ORFEO Toolbox library - OTBVectorDataBase 
i A libotbvectordataio-6.4-1        - ORFEO Toolbox library - OTBVectorDataIO   
p   libotbvectordataio-6.4-1:i386   - ORFEO Toolbox library - OTBVectorDataIO   
i A libotbwavelet-6.4-1             - ORFEO Toolbox library - OTBWavelet        
p   libotbwavelet-6.4-1:i386        - ORFEO Toolbox library - OTBWavelet        
i   otb-bin                         - ORFEO Toolbox command line applications   
p   otb-bin:i386                    - ORFEO Toolbox command line applications   
p   otb-bin-qt                      - ORFEO Toolbox graphical user interface app
p   otb-bin-qt:i386                 - ORFEO Toolbox graphical user interface app
i A otb-i18n                        - ORFEO Toolbox translations                
v   otb-i18n:i386                   -                                           
p   otb-testdriver                  - ORFEO Toolbox library - OTBTestDriver     
p   otb-testdriver:i386             - ORFEO Toolbox library - OTBTestDriver     
i   python-otb                      - ORFEO Toolbox Python API for applications 
p   python-otb:i386                 - ORFEO Toolbox Python API for applications 
i   python3-otb                     - ORFEO Toolbox Python API for applications 
p   python3-otb:i386                - ORFEO Toolbox Python API for applications 
p   tuxfootball                     - great 2D soccer (sometimes called football
p   tuxfootball:i386                - great 2D soccer (sometimes called football
p   wesnoth-1.12-sotbe              - "Son of the Black-Eye" official campaign f

**Comment by nguyen0508** [comment]
Avec la liste des packages au dessus, il me semble la library OTB pour python3 est déjà installé. Cependant, quand je fais "import otbApplication as otb", il me retourne : 
>>> import otbApplication as otb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'otbApplication'

J'essais donc l'installer avec pip3 mais il me retourne une erreur suivante:
Collecting otb
 Using cached https://files.pythonhosted.org/packages/16/5d/18e5987a18e8e7b3c98cb49c4e447929e95972bec1869ba1eb6753019801/otb-0.2.1.tar.gz
Collecting numpy>=1.4 (from otb)
  Using cached https://files.pythonhosted.org/packages/9e/eb/c9eda9f4865d669e0bb37ce5c780e86c63daa54ca827b95a171429012d08/numpy-1.15.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting matplotlib>=1.1 (from otb)
  Using cached https://files.pythonhosted.org/packages/59/08/04933377dc4500e3698e93f9113dc3624874e0914f4c85767ecb5b389084/matplotlib-2.2.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting anfft (from otb)
  Could not find a version that satisfies the requirement anfft (from otb) (from versions: )
No matching distribution found for anfft (from otb)

Pourriez-vous me dire comment le bien installer, s'il vous plaît?

**Comment by dumasl** [comment]
Avez vous utiliser le script otbenv comme indiqué ici ?
https://www.orfeo-toolbox.org/CookBook/Installation.html#

Ce script doit permettre de monter correctemnt l'environnement otb pour python.
Notez que pour python 3 une petite modif est à réaliser comme indiqué dans la doc

**Comment by nguyen0508** [comment]
Je l'ai modifié de lib/python à lib/python3, pour le variable PYTHONPATH mais comme je ne connais pas très bien linux, je ne sais pas donc si j'ai bien défini les PATH pour l'installation. 

Voici mon fichier  otbenv.profile:

"CMAKE_PREFIX_PATH=/usr/local/OTB-6.6.0-Linux64
export CMAKE_PREFIX_PATH

# check and set OTB_APPLICATION_PATH
if [ -z "$OTB_APPLICATION_PATH" ] || [ "$OTB_APPLICATION_PATH" = "" ]; then
    OTB_APPLICATION_PATH=/usr/local/OTB-6.6.0-Linux64/lib/otb/applications
else
    OTB_APPLICATION_PATH=/usr/local/OTB-6.6.0-Linux64/lib/otb/applications:$OTB_APPLICATION_PATH
fi

# Add bin direcotory to system PATH
PATH=/usr/local/OTB-6.6.0-Linux64/bin:$PATH

# export PYTHONPATH to import otbApplication.py
PYTHONPATH=/usr/local/OTB-6.6.0-Linux64/lib/python3:$PYTHONPATH

# set numeric locale to C
LC_NUMERIC=C

# set GDAL_DATA variable used by otb application
GDAL_DATA=/usr/local/OTB-6.6.0-Linux64/share/gdal

export GDAL_DRIVER_PATH=disable

# set GEOTIFF_CSV variable used by otb application
GEOTIFF_CSV=/usr/local/OTB-6.6.0-Linux64/share/epsg_csv

# export variables
export LC_NUMERIC
export GDAL_DATA
export GEOTIFF_CSV
export OTB_APPLICATION_PATH
export PATH
export PYTHONPATH"
