### ISSUE TITLE
Classification du bundle avec l'OTB

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#5]
Une fois #4 réalisée, on peut classifier le bundle (PAN+XS) avec l'OTB.

**Comment by nguyen0508** [comment]
J'essais d'abourd d'avoir le bundle (PAN + XS) avec l'OTB avec le tutoriel sur "https://www.orfeo-toolbox.org/CookBook/recipes/optpreproc.html" mais je n'arrive toujours pas car il me retourne une erreur "undefined symbol".

"nguyen@nguyen-Inspiron-5545:~$ otbcli_BundleToPerfectSensor
/usr/bin/otbApplicationLauncherCommandLine: symbol lookup error: /usr/lib/x86_64-linux-gnu/libotbossimplugins-6.4.so.1: undefined symbol: _ZN16ossimSensorModel12getObsCovMatERK8ossimDptRN6NEWMAT15SymmetricMatrixEd"

**Comment by dumasl** [comment]
je clos cette issue car l'étape est terminée
