### ISSUE TITLE
Manipulation image3D + image classifiée

### ISSUE THREAD

**Issue by dumasl** [CS-SI/2018_insa_5gmm_schoolproject#7]
Ici l'idée est de manipuler les sorties de #1 et #5 communément pour pouvoir améliorer le nuage 3D.

image 3D
========
**cf. doc pour lecture d'un fichier netcdf .nc**
http://xarray.pydata.org/en/stable/

L'idée est d'ouvrir une des images3D .nc issue de #1  avec python et le module xarray.

image classifiée
============
L'idée est d'utiliser cette l'image provenant de #5 et l'ouvrir également avec python (gdal est une bonne option mais on peut lire une image de nombreuses manières différentes en python)

utilisation commune
================
L'objectif ici est d'avoir les deux images (3D et classifiée) sur la même emprise.
- L'image 3D est superposable à l'image référence donnée à s2p (image numéro 1 dans le config.son #1)
- L'image classifiée est nécessairement superposable à l'image donnée en entrée de l'otb (#3 #5)
Donc si on met une roi dans le config.json de s2p, il faut la même roi dans l'étape de classification otb.

**Comment by nguyen0508** [comment]
Monsieur,

J'ai fait extraire une ROI (de taille 500x500) de nos images PAN et ensuite j'ai lancé s2p sur ces images coupées pour créer des nuages de points 3D. J'ai utilisé ensuite le Kmeans de OTB sur l'image PMS pour créer des classes pour chaque points. Tous les résultats, j'ai essayé de visualiser avec ce notebook: "https://github.com/nguyen0508/2018_insa_5gmm_schoolproject/blob/master/read_data.ipynb", J'essayerai lancer d'autre algorithme pour voir si les classes seront changées.

Pour la prochaine étape, est-ce que je dois faire utiliser ces classes pour améliorer le nuage des points ( c'est à dire d'ajuster la position x,y,z pour chaque point)? 
Si oui, pourriez-vous me donner des conseils pour le faire, s'il vous plaît?

**Comment by dumasl** [comment]
Imaginez que vous ayez 4 classes simples : eau, route, végétation, toiture

L'otb doit pouvoir vous fournir cela:
utilisez https://www.orfeo-toolbox.org/CookBook/Applications/app_ImageClassifier.html avec ce fichier de modèle https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb-data/blob/master/Input/Classification/clsvmModelQB1.svm comme pour l'exemple présenté ici https://www.orfeo-toolbox.org/CookBook/recipes/pbclassif.html#example

Ensuite je vous propose de réfléchir à comment améliorer le nuage de points sur ces classes.
On pourra commencer par les plus simples peut être (eau, route) puis plus complexes (toitures). Par exemple vos collègues de l'an dernier avaient travaillés sur les toitures. 

Par contre il vous noter que votre nuage de points est en coordonnées ECEF dans un repère depuis le centre de la terre. L'avez vous visualisé ? Via python ? Via monteverdi ? 
Il vous sera plus simple de changer de repère pour mieux voir les résultats. Par exemple passer en UTM.

**Comment by dumasl** [comment]
Très bien ! 

Demain nous tacherons de vous montrer comment visualiser ces points. 
Ceci dit il y a peut être des solutions offertes par matplotlib (pour des petites régions cela devrait marcher, par contre pour le nuage entier ça risque d'être juste)


De toute façon, il sera préférable d'identifier des zones pertinentes pour votre étude. Justement en essayant de détecter les points 3D qui semblent incorrects. L'idée serait de sélectionner des régions d'intérêt pour les différentes classes étudiées, et se concentrer sur ces régions pour voire si l'on arrive à améliorer le rendu du nuage de points.

**Comment by dumasl** [comment]
je clos cette issue car vous avez realise cette étape
